version: "3.9"
services:
    web:
        environment:    
            - ASPNETCORE_URLS=http://0.0.0.0:80
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
             - "8090:80"                               
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1434:1433
        environment:
            SA_PASSWORD: "LaVacaLoca16"
            ACCEPT_EULA: "Y"